import React, { useState } from 'react';
import { FileText, Printer, Download, Check, Sparkles, Copy, Layers } from 'lucide-react';
import { BusinessJSON, IntelligenceAnalysis } from '../types';

interface ReportViewProps {
  businessJson: BusinessJSON;
  analysis: IntelligenceAnalysis;
}

export const ReportView: React.FC<ReportViewProps> = ({
  businessJson,
  analysis
}) => {
  const [copiedMd, setCopiedMd] = useState(false);
  const b = businessJson.business;

  const generateMarkdownReport = () => {
    return `# BACS AI Strategy & Business Intelligence Report
**Business Name**: ${b.name}
**Industry**: ${b.industry}
**Stage**: ${b.stage}
**Generated Date**: ${new Date().toLocaleDateString()}

---

## 1. BACS Stage-Aware Decision Engine Verdict
- **Decision Verdict**: ${analysis.decisionEngine?.decision || 'Proceed with Validation'}
- **Customer Evidence Score**: ${analysis.decisionEngine?.customerEvidenceScore || 65}/100
- **Decision Rationale**: ${analysis.decisionEngine?.decisionRationale || 'Grounding decisions in empirical evidence.'}

### The 5 Core Decision Engine Answers:
1. **Should you build, fix, or scale?**: ${analysis.decisionEngine?.fiveCoreAnswers?.shouldBuildFixScale || 'Conduct low-cost customer experiments.'}
2. **What's the biggest leak limiting success?**: ${analysis.decisionEngine?.fiveCoreAnswers?.biggestLeak || 'Customer Retention & Onboarding Leak'}
3. **What's causing that leak?**: ${analysis.decisionEngine?.fiveCoreAnswers?.leakCause || 'Unverified assumptions.'}
4. **What's the cheapest validation experiment?**: ${analysis.decisionEngine?.fiveCoreAnswers?.cheapestExperiment || 'Deploy $100 validation pre-order page.'}
5. **What should you do this week?**: ${analysis.decisionEngine?.fiveCoreAnswers?.thisWeekActionPlan || 'Conduct 5 customer problem interviews.'}

---

## 2. Executive Summary & Diagnosis
- **BACS Index Score**: ${analysis.bacsIndexScore}/100
- **Overall Business Health**: ${analysis.overallHealthScore}%
- **AI Confidence Rating**: ${analysis.aiConfidence}%

### Executive Summary
${analysis.executiveSummary}

---

## 2. One Thing to Fix First
- **Title**: ${analysis.oneThingToFix?.title || 'Validate Pricing & Unit Economics'}
- **Why It Matters**: ${analysis.oneThingToFix?.whyItMatters || 'Unit economics dictate CAC margin buffer.'}
- **Expected Impact**: ${analysis.oneThingToFix?.expectedImpact || 'Protects gross margins.'}
- **Action Step**: ${analysis.oneThingToFix?.actionStep || 'Run pre-order campaign.'}

---

## 3. Hidden Business Assumptions™ (Top 3 Core Hypotheses)
${analysis.realityCheck
  .map(
    (item, idx) => `
### Hypothesis #${idx + 1}: "${item.assumption}"
- **Why It Matters**: ${item.whyItMatters}
- **Risk If Wrong**: ${item.riskIfWrong}
- **Low-Cost Validation Experiment**: ${item.lowCostExperiment}
`
  )
  .join('')}

---

## 4. 12-Dimension Score Matrix
${analysis.scores
  .map((s) => `- **${s.title}**: ${s.score}/100 (Risk Level: ${s.priority})\n  *Recommended Action*: ${s.recommendedAction}`)
  .join('\n')}

---

## 5. Strengths & Weaknesses
### Strengths
${analysis.strengths.map((s) => `- ${s}`).join('\n')}

### Weaknesses
${analysis.weaknesses.map((w) => `- ${w}`).join('\n')}

---

## 6. 90-Day Execution Roadmap
${analysis.roadmap
  .map(
    (r) => `
### ${r.phase} (${r.duration}): ${r.title} [Focus: ${r.focusArea}]
${r.items.map((it) => `- ${it}`).join('\n')}
`
  )
  .join('')}

---
*Report generated by BACS AI Business Consultant • BuildFest 2026*
`;
  };

  const handleCopyMarkdown = () => {
    navigator.clipboard.writeText(generateMarkdownReport());
    setCopiedMd(true);
    setTimeout(() => setCopiedMd(false), 2000);
  };

  const handleDownloadMarkdown = () => {
    const md = generateMarkdownReport();
    const blob = new Blob([md], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${b.name.toLowerCase().replace(/\s+/g, '_')}_bacs_diagnosis.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="space-y-6 max-w-5xl mx-auto py-4 px-4 sm:px-6">
      {/* Header */}
      <div className="bg-slate-900 border border-slate-800 rounded-3xl p-6 shadow-xl flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
        <div>
          <div className="flex items-center space-x-2">
            <span className="text-[10px] font-bold uppercase tracking-wider px-2.5 py-0.5 rounded-full bg-purple-500/20 text-purple-300 border border-purple-500/30">
              Executive Report
            </span>
            <span className="text-xs font-mono text-slate-400">
              Generated {new Date().toLocaleDateString()}
            </span>
          </div>
          <h1 className="text-2xl sm:text-3xl font-extrabold text-white tracking-tight mt-1">
            Strategy & Diagnosis Report
          </h1>
          <p className="text-xs text-slate-400 mt-1">
            Exportable Markdown document and printable PDF report for {b.name}.
          </p>
        </div>

        <div className="flex items-center space-x-2 w-full md:w-auto">
          <button
            onClick={handlePrint}
            className="px-4 py-2.5 rounded-xl bg-purple-600 hover:bg-purple-700 text-white text-xs font-bold flex items-center space-x-1.5 shadow-md transition"
          >
            <Printer className="w-4 h-4" />
            <span>Print / Save PDF</span>
          </button>

          <button
            onClick={handleCopyMarkdown}
            className="px-3.5 py-2.5 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-semibold border border-slate-700 flex items-center space-x-1.5 transition"
          >
            {copiedMd ? <Check className="w-4 h-4 text-emerald-400" /> : <Copy className="w-4 h-4" />}
            <span>{copiedMd ? 'Copied' : 'Copy MD'}</span>
          </button>

          <button
            onClick={handleDownloadMarkdown}
            className="px-3.5 py-2.5 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-semibold border border-slate-700 flex items-center space-x-1.5 transition"
          >
            <Download className="w-4 h-4" />
            <span>Download .md</span>
          </button>
        </div>
      </div>

      {/* Printable Formatted Report Box */}
      <div className="bg-slate-900 border border-slate-800 rounded-3xl p-8 space-y-8 shadow-xl text-slate-200">
        <div className="border-b border-slate-800 pb-6 flex justify-between items-start">
          <div>
            <span className="text-xs uppercase font-extrabold text-purple-400 tracking-wider font-mono">
              BACS AI Business Diagnosis Report
            </span>
            <h2 className="text-3xl font-extrabold text-white mt-1">
              {b.name}
            </h2>
            <p className="text-xs text-slate-400 mt-1">
              {b.industry} • {b.stage} Stage • Grounded in Business JSON
            </p>
          </div>

          <div className="text-right">
            <div className="text-3xl font-extrabold text-purple-400 font-mono">
              {analysis.bacsIndexScore}/100
            </div>
            <span className="text-[10px] text-slate-400 font-bold uppercase tracking-wider">BACS Index Score</span>
          </div>
        </div>

        {/* Executive Summary */}
        <div className="space-y-3">
          <h3 className="text-sm font-bold text-white uppercase tracking-wider border-b border-slate-800 pb-2 flex items-center space-x-2">
            <FileText className="w-4 h-4 text-purple-400" />
            <span>1. Executive Diagnosis Summary</span>
          </h3>
          <p className="text-xs sm:text-sm text-slate-300 leading-relaxed bg-slate-950/60 p-4 rounded-xl border border-slate-800">
            {analysis.executiveSummary}
          </p>
        </div>

        {/* Hidden Business Assumptions */}
        <div className="space-y-3">
          <h3 className="text-sm font-bold text-white uppercase tracking-wider border-b border-slate-800 pb-2">
            2. Hidden Business Assumptions™
          </h3>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            {analysis.realityCheck.map((item, i) => (
              <div key={i} className="bg-slate-950/60 p-4 rounded-xl border border-slate-800 space-y-2 text-xs">
                <span className="font-bold text-purple-300">#{i + 1} "{item.assumption}"</span>
                <p className="text-slate-400"><strong>Risk:</strong> {item.riskIfWrong}</p>
                <p className="text-emerald-400"><strong>Experiment:</strong> {item.lowCostExperiment}</p>
              </div>
            ))}
          </div>
        </div>

        {/* 90-Day Strategic Roadmap */}
        <div className="space-y-3">
          <h3 className="text-sm font-bold text-white uppercase tracking-wider border-b border-slate-800 pb-2">
            3. 90-Day Execution Roadmap
          </h3>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4 text-xs">
            {analysis.roadmap.map((phase, idx) => (
              <div key={idx} className="bg-slate-950/60 p-4 rounded-xl border border-slate-800 space-y-2">
                <span className="font-bold text-purple-300">{phase.phase}: {phase.title}</span>
                <ul className="space-y-1 text-slate-400">
                  {phase.items.map((it, i) => (
                    <li key={i}>• {it}</li>
                  ))}
                </ul>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
};
