import React, { useState } from 'react';
import { X, Printer, Download, FileText, Check, Sparkles } from 'lucide-react';
import { BusinessJSON, IntelligenceAnalysis } from '../types';

interface ReportExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  businessJson: BusinessJSON;
  analysis: IntelligenceAnalysis;
}

export const ReportExportModal: React.FC<ReportExportModalProps> = ({
  isOpen,
  onClose,
  businessJson,
  analysis
}) => {
  const [copiedMd, setCopiedMd] = useState(false);

  if (!isOpen) return null;

  const b = businessJson.business;

  const generateMarkdownReport = () => {
    return `# BACS AI Business Diagnosis Report
**Business Name**: ${b.name}
**Industry**: ${b.industry}
**Stage**: ${b.stage}
**Generated Date**: ${new Date().toLocaleDateString()}

---

## 1. Executive Summary & Scores
- **BACS Index Score**: ${analysis.bacsIndexScore}/100
- **Overall Business Health**: ${analysis.overallHealthScore}%
- **AI Confidence Rating**: ${analysis.aiConfidence}%

### Executive Summary
${analysis.executiveSummary}

---

## 2. Reality Check (Top 3 Unvalidated Assumptions)
${analysis.realityCheck
  .map(
    (item, idx) => `
### Assumption #${idx + 1}: "${item.assumption}"
- **Why It Matters**: ${item.whyItMatters}
- **Risk If Wrong**: ${item.riskIfWrong}
- **Low-Cost Experiment**: ${item.lowCostExperiment}
`
  )
  .join('')}

---

## 3. Category Score Breakdown
${analysis.scores
  .map((s) => `- **${s.title}**: ${s.score}/100 (Priority: ${s.priority})\n  *Action*: ${s.recommendedAction}`)
  .join('\n')}

---

## 4. Strengths & Weaknesses
### Strengths
${analysis.strengths.map((s) => `- ${s}`).join('\n')}

### Weaknesses
${analysis.weaknesses.map((w) => `- ${w}`).join('\n')}

---

## 5. High-Impact Quick Wins
${analysis.quickWins.map((qw, idx) => `${idx + 1}. ${qw}`).join('\n')}

---

## 6. 90-Day Execution Roadmap
${analysis.roadmap
  .map(
    (r) => `
### ${r.phase} (${r.duration}): ${r.title} [Focus: ${r.focusArea}]
${r.items.map((it) => `- ${it}`).join('\n')}
`
  )
  .join('')}

---
*Report generated by BACS AI Business Consultant • BuildFest 2026*
`;
  };

  const handleCopyMarkdown = () => {
    navigator.clipboard.writeText(generateMarkdownReport());
    setCopiedMd(true);
    setTimeout(() => setCopiedMd(false), 2000);
  };

  const handleDownloadMarkdown = () => {
    const md = generateMarkdownReport();
    const blob = new Blob([md], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${b.name.toLowerCase().replace(/\s+/g, '_')}_bacs_diagnosis.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 z-50 overflow-y-auto bg-slate-900/60 backdrop-blur-xs flex items-center justify-center p-4 print:p-0 print:static print:bg-white">
      <div className="bg-white dark:bg-slate-900 w-full max-w-4xl rounded-3xl shadow-2xl border border-slate-200 dark:border-slate-800 overflow-hidden space-y-4 my-8 animate-in fade-in zoom-in-95 duration-200 print:shadow-none print:border-none print:my-0">
        {/* Header */}
        <div className="p-6 border-b border-slate-200 dark:border-slate-800 flex items-center justify-between bg-slate-50 dark:bg-slate-900/90 print:hidden">
          <div className="flex items-center space-x-3">
            <div className="w-10 h-10 rounded-xl bg-indigo-600 text-white flex items-center justify-center font-bold">
              <FileText className="w-5 h-5" />
            </div>
            <div>
              <h3 className="font-extrabold text-slate-900 dark:text-white text-lg">
                Export Diagnosis Report
              </h3>
              <p className="text-xs text-slate-500 dark:text-slate-400">
                Download as Markdown, print to PDF, or copy executive summary.
              </p>
            </div>
          </div>

          <div className="flex items-center space-x-2">
            <button
              onClick={handlePrint}
              className="px-3.5 py-2 rounded-xl bg-indigo-600 hover:bg-indigo-700 text-white text-xs font-bold flex items-center space-x-1 shadow-sm transition-all"
            >
              <Printer className="w-4 h-4" />
              <span>Print / PDF</span>
            </button>

            <button
              onClick={handleCopyMarkdown}
              className="px-3.5 py-2 rounded-xl bg-slate-100 dark:bg-slate-800 hover:bg-slate-200 text-slate-700 dark:text-slate-300 text-xs font-semibold flex items-center space-x-1 transition-all"
            >
              {copiedMd ? <Check className="w-4 h-4 text-emerald-500" /> : <Sparkles className="w-4 h-4 text-indigo-500" />}
              <span>{copiedMd ? 'Copied' : 'Copy Markdown'}</span>
            </button>

            <button
              onClick={handleDownloadMarkdown}
              className="px-3.5 py-2 rounded-xl bg-slate-100 dark:bg-slate-800 hover:bg-slate-200 text-slate-700 dark:text-slate-300 text-xs font-semibold flex items-center space-x-1 transition-all"
            >
              <Download className="w-4 h-4 text-slate-500" />
              <span>Download .md</span>
            </button>

            <button
              onClick={onClose}
              className="p-2 rounded-xl text-slate-400 hover:bg-slate-200 dark:hover:bg-slate-800 transition-colors"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Printable Formatted Preview */}
        <div className="p-8 space-y-8 bg-white dark:bg-slate-900 text-slate-900 dark:text-white max-h-[600px] overflow-y-auto print:max-h-none print:overflow-visible">
          <div className="border-b border-slate-200 dark:border-slate-800 pb-6 space-y-2">
            <div className="flex justify-between items-start">
              <div>
                <span className="text-xs uppercase font-extrabold text-indigo-600 dark:text-indigo-400 tracking-wider">
                  BACS AI Business Diagnosis Report
                </span>
                <h1 className="text-3xl font-extrabold text-slate-900 dark:text-white mt-1">
                  {b.name}
                </h1>
                <p className="text-sm text-slate-500 dark:text-slate-400">
                  {b.industry} • {b.stage} Stage • Generated {new Date().toLocaleDateString()}
                </p>
              </div>

              <div className="text-right">
                <div className="text-3xl font-extrabold text-indigo-600 dark:text-indigo-400">
                  {analysis.bacsIndexScore}/100
                </div>
                <span className="text-xs text-slate-400 font-semibold uppercase">BACS Index</span>
              </div>
            </div>
          </div>

          <div className="space-y-4">
            <h3 className="text-lg font-bold border-b border-slate-200 dark:border-slate-800 pb-2">
              Executive Diagnosis Summary
            </h3>
            <p className="text-sm text-slate-600 dark:text-slate-300 leading-relaxed">
              {analysis.executiveSummary}
            </p>
          </div>

          <div className="space-y-4">
            <h3 className="text-lg font-bold border-b border-slate-200 dark:border-slate-800 pb-2">
              Reality Check: Top 3 Core Assumptions
            </h3>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              {analysis.realityCheck.map((item, i) => (
                <div key={i} className="p-4 rounded-xl bg-slate-50 dark:bg-slate-800/60 border border-slate-200 dark:border-slate-700 space-y-2 text-xs">
                  <span className="font-bold text-indigo-600 dark:text-indigo-400">#{i + 1} "{item.assumption}"</span>
                  <p><strong>Risk:</strong> {item.riskIfWrong}</p>
                  <p className="text-emerald-600 dark:text-emerald-400"><strong>Experiment:</strong> {item.lowCostExperiment}</p>
                </div>
              ))}
            </div>
          </div>

          <div className="space-y-4">
            <h3 className="text-lg font-bold border-b border-slate-200 dark:border-slate-800 pb-2">
              90-Day Strategic Roadmap
            </h3>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4 text-xs">
              {analysis.roadmap.map((phase, idx) => (
                <div key={idx} className="p-4 rounded-xl border border-slate-200 dark:border-slate-700 space-y-2">
                  <span className="font-bold text-indigo-600 dark:text-indigo-400">{phase.phase}: {phase.title}</span>
                  <ul className="space-y-1">
                    {phase.items.map((it, i) => (
                      <li key={i}>• {it}</li>
                    ))}
                  </ul>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
